apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: certifyedge-staging
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: certifyedge-staging
        environment: staging

    rule_files:
      - /etc/prometheus/rules/*.yml

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

    scrape_configs:
      # CertifyEdge Services
      - job_name: 'stl-compiler'
        static_configs:
          - targets: ['stl-compiler:8080']
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s

      - job_name: 'smt-verifier'
        static_configs:
          - targets: ['smt-verifier:8080']
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s

      - job_name: 'certificate-service'
        static_configs:
          - targets: ['certificate:8080']
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s

      - job_name: 'auditor-api'
        static_configs:
          - targets: ['auditor-api:8080']
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s

      - job_name: 'lean-autoprover'
        static_configs:
          - targets: ['lean-autoprover:8080']
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s

      - job_name: 'gpu-farm'
        static_configs:
          - targets: ['gpu-farm:8080']
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s

      - job_name: 'grid-in-loop'
        static_configs:
          - targets: ['grid-in-loop:8080']
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s

      # Kubernetes Components
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

      # GPU Monitoring
      - job_name: 'nvidia-gpu'
        static_configs:
          - targets: ['nvidia-dcgm-exporter:9400']
        scrape_interval: 5s
        scrape_timeout: 3s

      # Database Monitoring
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter:9187']
        scrape_interval: 15s

      # Redis Monitoring
      - job_name: 'redis'
        static_configs:
          - targets: ['redis-exporter:9121']
        scrape_interval: 15s

      # Node Exporter
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
        static_configs:
          - targets: ['node-exporter:9100']

      # Kube-state-metrics
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics:8080']
        scrape_interval: 30s

      # cAdvisor
      - job_name: 'cadvisor'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
        static_configs:
          - targets: ['cadvisor:8080']

  rules.yml: |
    groups:
      - name: certifyedge.rules
        rules:
          # Service Health Alerts
          - alert: ServiceDown
            expr: up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Service {{ $labels.job }} is down"
              description: "Service {{ $labels.job }} has been down for more than 1 minute."

          # High Error Rate
          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High error rate for {{ $labels.job }}"
              description: "Error rate is {{ $value }} errors per second"

          # High Response Time
          - alert: HighResponseTime
            expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High response time for {{ $labels.job }}"
              description: "95th percentile response time is {{ $value }} seconds"

          # GPU Utilization
          - alert: HighGPUUtilization
            expr: DCGM_FI_DEV_GPU_UTIL > 90
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High GPU utilization"
              description: "GPU {{ $labels.gpu }} is {{ $value }}% utilized"

          # Memory Usage
          - alert: HighMemoryUsage
            expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage on {{ $labels.instance }}"
              description: "Memory usage is {{ $value | humanizePercentage }}"

          # Disk Usage
          - alert: HighDiskUsage
            expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.85
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High disk usage on {{ $labels.instance }}"
              description: "Disk usage is {{ $value | humanizePercentage }}"

          # Certificate Expiry
          - alert: CertificateExpiringSoon
            expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Certificate expiring soon"
              description: "Certificate will expire in {{ $value | humanizeDuration }}"

          # SMT Solver Health
          - alert: SMTSolverUnhealthy
            expr: smt_solver_health == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "SMT solver is unhealthy"
              description: "SMT solver {{ $labels.solver }} is not responding"

          # Lean Prover Health
          - alert: LeanProverUnhealthy
            expr: lean_prover_health == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Lean prover is unhealthy"
              description: "Lean prover is not responding"

          # Grid Simulation Health
          - alert: GridSimulationUnhealthy
            expr: grid_simulation_health == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Grid simulation is unhealthy"
              description: "Grid simulation service is not responding"

          # Certificate Generation Rate
          - alert: LowCertificateGenerationRate
            expr: rate(certificates_generated_total[5m]) < 0.1
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Low certificate generation rate"
              description: "Certificate generation rate is {{ $value }} per second"

          # Proof Verification Rate
          - alert: LowProofVerificationRate
            expr: rate(proofs_verified_total[5m]) < 0.1
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Low proof verification rate"
              description: "Proof verification rate is {{ $value }} per second" 