//! LabTrust deterministic release fixtures and runbook CLI smoke tests.
//!
//! Canonical PCS RC fixtures (`trace.json`, `trace_certificate.json`) are synced from
//! `pcs-core/examples/labtrust-release/` via `make sync-pcs-core-rc`. Negative traces are
//! regenerated by `cargo test -p certifyedge-integration write_fixtures -- --ignored --nocapture`.

use assert_cmd::Command;
use pcs_certificate::{
    is_placeholder_source_commit, is_zero_source_commit, labtrust_gym_root, ZERO_SOURCE_COMMIT,
};

use predicates::prelude::*;

#[path = "../common/support.rs"]
mod support;

use support::{
    assert_certificate_semantics_equal, certifyedge_cmd, env_lock, git_head_commit,
    labtrust_fixture, labtrust_release_certificate_fixture, labtrust_release_fixture,
    pcs_core_rc_manifest_certifyedge_commit, repo_root,
    runbook_labtrust_release_trace, runbook_spec_qc_release, validate_certificate_against_pcs_core,
    validate_labtrust_release_fixture_tree, with_source_commit,
};

const ENV_OVERRIDE_COMMIT: &str = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef";

fn certifyedge() -> Command {
    certifyedge_cmd()
}

fn emit_release_args(out: &std::path::Path) -> Vec<String> {
    vec![
        "--release-mode".into(),
        "emit-pcs-certificate".into(),
        "--spec".into(),
        runbook_spec_qc_release().to_string_lossy().into_owned(),
        "--trace".into(),
        runbook_labtrust_release_trace()
            .to_string_lossy()
            .into_owned(),
        "--out".into(),
        out.to_string_lossy().into_owned(),
    ]
}

/// Exact runbook: check-trace → emit-pcs-certificate → verify-certificate --trace
#[test]
fn test_cli_labtrust_release_runbook_smoke() {
    let trace = runbook_labtrust_release_trace();
    let spec = runbook_spec_qc_release();
    let cert_out = repo_root().join("target/trace_certificate.json");

    certifyedge()
        .args([
            "check-trace",
            "--spec",
            spec.to_str().unwrap(),
            "--trace",
            trace.to_str().unwrap(),
        ])
        .assert()
        .success()
        .stdout(predicate::str::contains("PASS"));

    with_source_commit(&pcs_core_rc_manifest_certifyedge_commit(), || {
        certifyedge()
            .args(emit_release_args(&cert_out))
            .assert()
            .success()
            .stdout(predicate::str::contains("source_commit_resolution=env"))
            .stdout(predicate::str::contains("CertificateChecked"));
    });

    validate_certificate_against_pcs_core(&cert_out);

    certifyedge()
        .args([
            "verify-certificate",
            cert_out.to_str().unwrap(),
            "--trace",
            trace.to_str().unwrap(),
        ])
        .assert()
        .success();
}

#[test]
fn test_labtrust_release_fixture_tree_validates() {
    validate_labtrust_release_fixture_tree();
}

#[test]
fn test_labtrust_release_trace_matches_labtrust_gym_export() {
    let release: serde_json::Value =
        serde_json::from_str(
            &std::fs::read_to_string(labtrust_release_fixture("trace.json")).unwrap(),
        )
            .unwrap();
    let gym: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(labtrust_fixture("valid_trace.json")).unwrap(),
    )
    .unwrap();
    assert_eq!(
        release["trace_hash"], gym["trace_hash"],
        "labtrust-release trace must match tests/labtrust/valid_trace.json (LabTrust-Gym export)"
    );
}

#[test]
fn test_labtrust_release_certificate_fixture_is_cli_generated() {
    let fixture = labtrust_release_certificate_fixture();
    let fixture_value: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&fixture).unwrap()).unwrap();
    assert_eq!(
        fixture_value["source_commit"].as_str().unwrap(),
        pcs_core_rc_manifest_certifyedge_commit()
    );

    certifyedge()
        .args([
            "verify-certificate",
            fixture.to_str().unwrap(),
            "--trace",
            labtrust_release_fixture("trace.json").to_str().unwrap(),
        ])
        .assert()
        .success();

    let out = repo_root().join("target/labtrust_release_reemit.json");
    with_source_commit(&pcs_core_rc_manifest_certifyedge_commit(), || {
        certifyedge()
            .args(emit_release_args(&out))
            .assert()
            .success();
    });

    let emitted: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&out).unwrap()).unwrap();
    assert_certificate_semantics_equal(&emitted, &fixture_value);
}

#[test]
fn test_labtrust_release_invalid_missing_qc_counterexample() {
    assert_check_trace_counterexample(
        "invalid_missing_qc_trace.json",
        "invalid_missing_qc_counterexample.json",
        "release_before_qc",
    );
}

#[test]
fn test_labtrust_release_invalid_unauthorized_counterexample() {
    assert_check_trace_counterexample(
        "invalid_unauthorized_trace.json",
        "invalid_unauthorized_counterexample.json",
        "unauthorized_release",
    );
}

#[test]
fn test_labtrust_release_invalid_traces_emit_rejected() {
    let spec = runbook_spec_qc_release();
    for trace_name in [
        "invalid_missing_qc_trace.json",
        "invalid_unauthorized_trace.json",
    ] {
        let out = repo_root()
            .join("target")
            .join(format!("rejected_{trace_name}"));
        let cx_out = repo_root()
            .join("target")
            .join(format!("rejected_cx_{trace_name}"));
        certifyedge()
            .args([
                "emit-pcs-certificate",
                "--spec",
                spec.to_str().unwrap(),
                "--trace",
                labtrust_release_fixture(trace_name).to_str().unwrap(),
                "--out",
                out.to_str().unwrap(),
                "--counterexample-out",
                cx_out.to_str().unwrap(),
            ])
            .assert()
            .success()
            .stdout(predicate::str::contains("Rejected"));

        let cert: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&out).unwrap()).unwrap();
        assert_eq!(cert["status"], "Rejected");
        assert!(cert["counterexample_ref"].is_string());
        assert!(cx_out.is_file());

        let cx: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&cx_out).unwrap()).unwrap();
        assert!(cx["reason"].is_string());
        assert!(cx["counterexample_id"].is_string());
    }
}

#[test]
fn test_release_mode_uses_certifyedge_git_commit() {
    let out = repo_root().join("target/release_git_labtrust_release.json");
    let head = git_head_commit().expect("CertifyEdge git HEAD required for this test");

    let _guard = env_lock();
    std::env::remove_var("CERTIFYEDGE_SOURCE_COMMIT");

    certifyedge()
        .args(emit_release_args(&out))
        .assert()
        .success()
        .stdout(predicate::str::contains("source_commit_resolution=git"));

    let cert: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&out).unwrap()).unwrap();
    assert_eq!(cert["source_commit"].as_str().unwrap(), head);
}

#[test]
fn test_release_mode_env_commit_overrides_git_commit() {
    let out = repo_root().join("target/release_env_override_labtrust_release.json");
    let head = git_head_commit().expect("CertifyEdge git HEAD");
    if head == ENV_OVERRIDE_COMMIT {
        eprintln!("skip: git HEAD equals override test commit");
        return;
    }

    with_source_commit(ENV_OVERRIDE_COMMIT, || {
        certifyedge()
            .args(emit_release_args(&out))
            .assert()
            .success()
            .stdout(predicate::str::contains("source_commit_resolution=env"));
    });

    let cert: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&out).unwrap()).unwrap();
    assert_eq!(cert["source_commit"].as_str().unwrap(), ENV_OVERRIDE_COMMIT);
}

#[test]
fn test_release_mode_rejects_labtrust_commit_if_explicit_repo_check_available() {
    let lt_root = match labtrust_gym_root() {
        Some(root) => root,
        None => {
            eprintln!("skip: LabTrust-Gym checkout not available for foreign-commit check");
            return;
        }
    };
    let lt_head = git_head_commit_in(&lt_root).expect("LabTrust-Gym git HEAD");
    let ce_head = git_head_commit().expect("CertifyEdge git HEAD");
    if lt_head == ce_head {
        eprintln!("skip: LabTrust-Gym HEAD equals CertifyEdge HEAD");
        return;
    }

    let out = repo_root().join("target/release_labtrust_head_rejected.json");
    with_source_commit(&lt_head, || {
        certifyedge()
            .args(emit_release_args(&out))
            .assert()
            .failure()
            .stderr(predicate::str::contains("LabTrust-Gym HEAD"));
    });
}

#[test]
fn test_release_mode_rejects_placeholder_commit() {
    let out = repo_root().join("target/release_placeholder_labtrust_release.json");
    for placeholder in [
        "local-dev",
        ZERO_SOURCE_COMMIT,
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "cccccccccccccccccccccccccccccccccccccccc",
    ] {
        let path = out.with_file_name(format!(
            "release_placeholder_{}.json",
            placeholder.chars().take(8).collect::<String>()
        ));
        with_source_commit(placeholder, || {
            certifyedge()
                .args(emit_release_args(&path))
                .assert()
                .failure();
        });
    }
}

#[test]
fn test_trace_certificate_source_repo_is_certifyedge() {
    let cert: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(labtrust_release_certificate_fixture()).unwrap(),
    )
    .unwrap();
    assert_eq!(
        cert["source_repo"].as_str().unwrap(),
        "https://github.com/fraware/CertifyEdge"
    );
}

#[test]
fn test_trace_certificate_source_commit_is_not_placeholder() {
    let cert: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(labtrust_release_certificate_fixture()).unwrap(),
    )
    .unwrap();
    let commit = cert["source_commit"].as_str().unwrap();
    assert!(!is_placeholder_source_commit(commit));
    assert!(!is_zero_source_commit(commit));
    assert_eq!(commit, pcs_core_rc_manifest_certifyedge_commit().as_str());
}

fn git_head_commit_in(root: &std::path::Path) -> Option<String> {
    let output = std::process::Command::new("git")
        .args(["-C", root.to_str()?, "rev-parse", "HEAD"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let commit = String::from_utf8_lossy(&output.stdout).trim().to_string();
    (commit.len() >= 7).then_some(commit)
}

fn assert_check_trace_counterexample(trace_file: &str, fixture_cx_file: &str, reason: &str) {
    let spec = runbook_spec_qc_release();
    let out_cx = repo_root()
        .join("target")
        .join(format!("cx_check_{trace_file}"));

    certifyedge()
        .args([
            "check-trace",
            "--spec",
            spec.to_str().unwrap(),
            "--trace",
            labtrust_release_fixture(trace_file).to_str().unwrap(),
            "--counterexample-out",
            out_cx.to_str().unwrap(),
        ])
        .assert()
        .failure();

    let expected: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(labtrust_release_fixture(fixture_cx_file)).unwrap(),
    )
    .unwrap();
    let actual: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&out_cx).unwrap()).unwrap();
    assert_eq!(expected["reason"], reason);
    assert_eq!(actual["reason"], reason);
    assert_eq!(actual["property_id"], expected["property_id"]);
    assert!(actual["counterexample_id"].is_string());
    assert!(actual["violating_event_id"].is_string());
}
