//! LabTrust deterministic release fixtures and runbook CLI smoke tests.
//!
//! Fixtures live under `tests/fixtures/labtrust-release/` and are regenerated by
//! `cargo test -p certifyedge-integration write_fixtures -- --ignored --nocapture`
//! (certificate and counterexamples are produced by the `certifyedge` CLI).

use assert_cmd::Command;
use pcs_certificate::{is_zero_source_commit, ZERO_SOURCE_COMMIT};
use predicates::prelude::*;

#[path = "../common/support.rs"]
mod support;

use support::{
    assert_certificate_semantics_equal, certifyedge_cmd, labtrust_fixture,
    labtrust_release_certificate_fixture, labtrust_release_fixture, pcs_cli_available, repo_root,
    runbook_labtrust_release_trace, runbook_spec_qc_release, validate_certificate_against_pcs_core,
    validate_labtrust_release_fixture_tree, with_source_commit, RELEASE_FIXTURE_SOURCE_COMMIT,
};

fn certifyedge() -> Command {
    certifyedge_cmd()
}

/// Exact runbook: check-trace → emit-pcs-certificate → verify-certificate --trace
#[test]
fn test_cli_labtrust_release_runbook_smoke() {
    let trace = runbook_labtrust_release_trace();
    let spec = runbook_spec_qc_release();
    let cert_out = repo_root().join("target/trace_certificate.json");

    certifyedge()
        .args([
            "check-trace",
            "--spec",
            spec.to_str().unwrap(),
            "--trace",
            trace.to_str().unwrap(),
        ])
        .assert()
        .success()
        .stdout(predicate::str::contains("PASS"));

    with_source_commit(RELEASE_FIXTURE_SOURCE_COMMIT, || {
        certifyedge()
            .args([
                "emit-pcs-certificate",
                "--spec",
                spec.to_str().unwrap(),
                "--trace",
                trace.to_str().unwrap(),
                "--out",
                cert_out.to_str().unwrap(),
            ])
            .assert()
            .success()
            .stdout(predicate::str::contains("CertificateChecked"));
    });

    validate_certificate_against_pcs_core(&cert_out);

    certifyedge()
        .args([
            "verify-certificate",
            cert_out.to_str().unwrap(),
            "--trace",
            trace.to_str().unwrap(),
        ])
        .assert()
        .success();
}

#[test]
fn test_labtrust_release_fixture_tree_validates() {
    validate_labtrust_release_fixture_tree();
}

#[test]
fn test_labtrust_release_trace_matches_labtrust_gym_export() {
    let release: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(labtrust_release_fixture("trace.json")).unwrap(),
    )
    .unwrap();
    let gym: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(labtrust_fixture("valid_trace.json")).unwrap(),
    )
    .unwrap();
    assert_eq!(
        release["trace_hash"], gym["trace_hash"],
        "labtrust-release trace must match tests/labtrust/valid_trace.json (LabTrust-Gym export)"
    );
}

#[test]
fn test_labtrust_release_certificate_fixture_is_cli_generated() {
    let fixture = labtrust_release_certificate_fixture();
    let fixture_value: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&fixture).unwrap()).unwrap();
    assert_eq!(
        fixture_value["source_commit"].as_str().unwrap(),
        RELEASE_FIXTURE_SOURCE_COMMIT
    );

    certifyedge()
        .args([
            "verify-certificate",
            fixture.to_str().unwrap(),
            "--trace",
            labtrust_release_fixture("trace.json").to_str().unwrap(),
        ])
        .assert()
        .success();

    let out = repo_root().join("target/labtrust_release_reemit.json");
    with_source_commit(RELEASE_FIXTURE_SOURCE_COMMIT, || {
        certifyedge()
            .args([
                "emit-pcs-certificate",
                "--spec",
                runbook_spec_qc_release().to_str().unwrap(),
                "--trace",
                runbook_labtrust_release_trace().to_str().unwrap(),
                "--out",
                out.to_str().unwrap(),
            ])
            .assert()
            .success();
    });

    let emitted: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&out).unwrap()).unwrap();
    assert_certificate_semantics_equal(&emitted, &fixture_value);
}

#[test]
fn test_labtrust_release_invalid_missing_qc_counterexample() {
    assert_check_trace_counterexample(
        "invalid_missing_qc_trace.json",
        "invalid_missing_qc_counterexample.json",
        "release_before_qc",
    );
}

#[test]
fn test_labtrust_release_invalid_unauthorized_counterexample() {
    assert_check_trace_counterexample(
        "invalid_unauthorized_trace.json",
        "invalid_unauthorized_counterexample.json",
        "unauthorized_release",
    );
}

#[test]
fn test_labtrust_release_invalid_traces_emit_rejected() {
    let spec = runbook_spec_qc_release();
    for trace_name in [
        "invalid_missing_qc_trace.json",
        "invalid_unauthorized_trace.json",
    ] {
        let out = repo_root()
            .join("target")
            .join(format!("rejected_{trace_name}"));
        let cx_out = repo_root()
            .join("target")
            .join(format!("rejected_cx_{trace_name}"));
        certifyedge()
            .args([
                "emit-pcs-certificate",
                "--spec",
                spec.to_str().unwrap(),
                "--trace",
                labtrust_release_fixture(trace_name).to_str().unwrap(),
                "--out",
                out.to_str().unwrap(),
                "--counterexample-out",
                cx_out.to_str().unwrap(),
            ])
            .assert()
            .success()
            .stdout(predicate::str::contains("Rejected"));

        let cert: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&out).unwrap()).unwrap();
        assert_eq!(cert["status"], "Rejected");
        assert!(cert["counterexample_ref"].is_string());
        assert!(cx_out.is_file());

        let cx: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&cx_out).unwrap()).unwrap();
        assert!(cx["reason"].is_string());
        assert!(cx["counterexample_id"].is_string());
    }
}

#[test]
fn test_release_mode_rejects_zero_source_commit_on_labtrust_release_trace() {
    let out = repo_root().join("target/release_zero_labtrust_release.json");
    with_source_commit(ZERO_SOURCE_COMMIT, || {
        certifyedge()
            .arg("--release-mode")
            .args([
                "emit-pcs-certificate",
                "--spec",
                runbook_spec_qc_release().to_str().unwrap(),
                "--trace",
                runbook_labtrust_release_trace().to_str().unwrap(),
                "--out",
                out.to_str().unwrap(),
            ])
            .assert()
            .failure();
    });
}

#[test]
fn test_release_mode_accepts_real_commit_on_labtrust_release_trace() {
    let out = repo_root().join("target/release_real_labtrust_release.json");
    let real_commit = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef";

    with_source_commit(real_commit, || {
        certifyedge()
            .arg("--release-mode")
            .args([
                "emit-pcs-certificate",
                "--spec",
                runbook_spec_qc_release().to_str().unwrap(),
                "--trace",
                runbook_labtrust_release_trace().to_str().unwrap(),
                "--out",
                out.to_str().unwrap(),
            ])
            .assert()
            .success();
    });

    if pcs_cli_available() {
        validate_certificate_against_pcs_core(&out);
    }

    let cert: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&out).unwrap()).unwrap();
    assert_eq!(cert["source_commit"].as_str().unwrap(), real_commit);
    assert!(!is_zero_source_commit(
        &cert["source_commit"].as_str().unwrap()
    ));
}

fn assert_check_trace_counterexample(trace_file: &str, fixture_cx_file: &str, reason: &str) {
    let spec = runbook_spec_qc_release();
    let out_cx = repo_root()
        .join("target")
        .join(format!("cx_check_{trace_file}"));

    certifyedge()
        .args([
            "check-trace",
            "--spec",
            spec.to_str().unwrap(),
            "--trace",
            labtrust_release_fixture(trace_file).to_str().unwrap(),
            "--counterexample-out",
            out_cx.to_str().unwrap(),
        ])
        .assert()
        .failure();

    let expected: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(labtrust_release_fixture(fixture_cx_file)).unwrap(),
    )
    .unwrap();
    let actual: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&out_cx).unwrap()).unwrap();
    assert_eq!(expected["reason"], reason);
    assert_eq!(actual["reason"], reason);
    assert_eq!(actual["property_id"], expected["property_id"]);
    assert!(actual["counterexample_id"].is_string());
    assert!(actual["violating_event_id"].is_string());
}
